version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    volumes:
     - ./:/usr/app
     - /usr/app/node_modules
    env_file:
      - ./.env